### ISSUE TITLE
xz version?

### ISSUE THREAD

**Issue by niallyoung** [skirsch/Czech#1]
G'day Steve, having some trouble on macOS with `xz` - what version/platform are you running on?

Would you be open to a PR, run xz via Docker image or similar - make this a bit more portable?

```
niall@localhost ~/git/Czech/code (main) $ make
Expanding source data file...
xz: ../data/CR_records.csv.xz: File format not recognized
make: *** [../data/CR_records.csv] Error 1

niall@localhost ~/git/Czech/data (main) $ xz -dk CR_records.csv.xz 
xz: CR_records.csv.xz: File format not recognized

# alternatives 
niall@localhost ~/git/Czech/data (main) $ brew install unar atool

niall@localhost ~/git/Czech/data (main) $ unar CR_records.csv.xz 
CR_records.csv.xz: Couldn't recognize the archive format.

niall@localhost ~/git/Czech/data (main) $ atool -x CR_records.csv.xz 
xz: CR_records.csv.xz: File format not recognized
atool: xz ... | CR_records.csv ...: non-zero return-code
```

**Comment by skirsch** [comment]
sure. I have managed PR's before but I can figure it out it out. Let me know if I have to do something to enable it.

**Comment by niallyoung** [comment]
Is `data/CR_records.csv.xz` corrupted, or using some strange new version? If not, it might be worth looking at bzip2 or another compression format - just for portability and ensuring we can all replicate

**Comment by skirsch** [comment]
standard xz

never had any problems.

if you can get as good compression on bzip2, open to using that.

**Comment by niallyoung** [comment]
Any idea what version of xz/xz-utils you're using locally? There was a backdoor introduced in 5.6.0/5.6.1 https://en.wikipedia.org/wiki/XZ_Utils_backdoor 

(once I can decompress I'll compare to bz2 and push up a PR 👍 )

**Comment by skirsch** [comment]
stk@stk-home:~/truenas-s3/backup-data/extracted files$ xz --version
xz (XZ Utils) 5.4.1
liblzma 5.4.1

**Comment by skirsch** [comment]
i run Debian under WSL on Windows. works like a charm.

**Comment by niallyoung** [comment]
ohhhhhhh I see the issue now, download via clone might be censored vs. https :\ 

https://github.com/skirsch/Czech/pull/2

**Comment by skirsch** [comment]
so do you still want me to add your pull request? It's sitting in the queue right now.. haven't looked at it yet.

**Comment by skirsch** [comment]
ok I merged in your changes. Thanks.

Give me a call when you get a moment: 650-279-1008.
